[project]
site_name = "CSCT Cloud"
site_url = "https://csctcloud.github.io/"

nav = [
  { "Introduction" = "index.md" },
  { "Getting started" = [
    { "Generating SSH keys" = "getting-started/generate-keys.md" },
    { "Installing Azure CLI" = "getting-started/install-azure-cli.md" },
    { "Copying keys to the server" = "getting-started/copy-keys.md" },
  ] },
  { "Connecting" = [
    { "Connect with the terminal" = "connecting/terminal.md" },
    { "Setup Visual Studio Code" = "connecting/vscode.md" },
  ] },
  { "MySQL" = [
    { "MySQL login details" = "mysql/login.md" },
    { "Using the MySQL shell" = "mysql/cli.md" },
    { "MySQL with a graphical interface" = "mysql/gui.md" },
  ] },
  { "Troubleshooting" = [
    { "Connection issues" = "troubleshooting/connecting.md" },
    { "Azure CLI" = "troubleshooting/azure-cli.md" },
  ] },
  { "Additional" = [
    { "Terminal programs" = "additional/terminals.md" },
    { "Port forwarding" = "additional/port-forwarding.md" },
    { "SSH configuration files" = "additional/ssh-config.md" },
    { "Installing OpenSSH" = "additional/install-openssh.md" },
  ] },
]

[project.theme]
favicon = "assets/favicon.ico"
language = "en"
features = [
  "content.code.copy",
  "content.footnote.tooltips",
  "content.tabs.link",
  "header.autohide",
  "navigation.footer",
  "navigation.sections",
  "navigation.tabs",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
]

[[project.theme.palette]]
scheme = "default"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "teal"
accent = "teal"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"
